### ISSUE TITLE
POI

### ISSUE THREAD

**Issue by wanzhixiao** [mingyangzhang/mv-region-embedding#1]
HI,
 In this paper,you said you compute the importance of each type of PoIs in a region using TF-IDF model by considering a PoI as word and a region as a document.

 In which source file is the original calculation method lies?

**Comment by mingyangzhang** [comment]
The preprocessing part is not in this repo. This is the API I used: https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfTransformer.html

**Comment by wanzhixiao** [comment]
> The preprocessing part is not in this repo. This is the API I used: https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfTransformer.html

could you paste this code  here? thanks！
