### ISSUE TITLE
How to preprocess the data?

### ISSUE THREAD

**Issue by zbzzbz** [mingyangzhang/mv-region-embedding#2]
How to preprocess the data?

**Comment by zbzzbz** [comment]
could you paste this code here? thanks！

**Comment by mingyangzhang** [comment]
> could you paste this code here? thanks！

hi, can you specify which data preprocessing steps are unclear to you?

**Comment by zbzzbz** [comment]
thanks, for example, how to generate NPY files in the project?

**Comment by CYBruce** [comment]
> thanks, for example, how to generate NPY files in the project?

Maybe the question is where can get the POI/block data and how to process them?

**Comment by zbzzbz** [comment]
> > thanks, for example, how to generate NPY files in the project?
> 
> Maybe the question is where can get the POI/block data and how to process them?

yes

**Comment by zbzzbz** [comment]
> > thanks, for example, how to generate NPY files in the project?
> 
> Maybe the question is where can get the POI/block data and how to process them?

yes.

**Comment by mingyangzhang** [comment]
> > > thanks, for example, how to generate NPY files in the project?
> > 
> > 
> > Maybe the question is where can get the POI/block data and how to process them?
> 
> yes.

**Comment by mingyangzhang** [comment]
POI data: https://data.cityofnewyork.us/City-Government/Points-Of-Interest/rxuy-2muj
Census block data will be uploaded later.  You can also search "Census block" on this website: https://opendata.cityofnewyork.us/
There are several similar data sources.
The data processing is quite straightforward. If you feel any step unclear, I can explain in detail.

**Comment by zbzzbz** [comment]
Is how to process the original data into NPY files？

**Comment by mingyangzhang** [comment]
> Is how to process the original data into NPY files？

The original scripts are very messed. I can attach a copy to you through email (send me an email first) as a reference, but I am afraid it wouldn't be very readable.

**Comment by zbzzbz** [comment]
Thank you. Please send your email address

**Comment by zbzzbz** [comment]
thank you，please give me your email address

**Comment by zbzzbz** [comment]
Hello, I sent you an email. I don't know if the address is accurate

**Comment by zbzzbz** [comment]
请问，签到数据集如何获取？
