### ISSUE TITLE
What's the hyper parameter settings? Cannot get the same results

### ISSUE THREAD

**Issue by CYBruce** [mingyangzhang/mv-region-embedding#3]
Following the code in this repository, I got
MAE:  73.69913821750217
RMSE:  100.33843768713176
R2:  0.5395111123848678
emb nmi: 0.761
emb ars: 0.572.
But the results is worse than the paper? Maybe the model is hyper-parameter sensitive. What's the settings in the paper?

**Comment by mingyangzhang** [comment]
Hi, parameters updated.

**Comment by zbzzbz** [comment]
兄弟，有联系方式吗？可以的话，想深入聊聊

**Comment by zbzzbz** [comment]
你好，有联系方式吗？可以的话，想深入聊聊

**Comment by CYBruce** [comment]
Still cannot get the expected results (The MAE is always higher than 70). Moreover, I think the dataset is too small with barely 180 regions and the results are strongly unstable using different random seeds.

**Comment by CYBruce** [comment]
Still cannot get the expected results (The MAE is always higher than 70). Moreover, I think the dataset is too small with barely 180 regions and the results are strongly unstable using different random seeds.
